version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.10
    
jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --include=dev
      - run:
          name: Build the project
          command: npm run build  
      - run:
          name: list files in build
          command: ls -la dist
      - run:
          name: Install Python and pip
          command: |
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
      - run:
          name: Install AWS EB CLI
          command: |
            pip3 install --upgrade pip
            pip3 install awsebcli --upgrade --user
            export PATH=$HOME/.local/bin:$PATH
      - run:
          name: Deploy to AWS Elastic Beanstalk
          command: |
            export PATH=$HOME/.local/bin:$PATH
            eb deploy aws-react-circleci-env

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy
          
